let reviewData = [
    {username:'JeffShepherd', summary: 'I am having performance issues sorting large datasets. Let me know how I may be able to improve efficiency in sorting.', email:'jeff.shep777@gmail.com', language:'Python', date:'01/24/2020', repo: 'https://github.com/JeffShepherd/Rancid-Tomatillos', status:'active', reviewer: 'Jackson'},
    {username:'jacksonmcguire', summary: 'Having issues passing setState in props. Can you please review how I use the context of this?', email:'lumbersexual@gmail.com', language:'JavaScript', date:'02/24/2021', repo: 'https://github.com/Jacksonmcguire/intention-timer', status:'', reviewer: ''},
    {username:'josharagon', summary: 'Please help me understand the use of conditionals in my project', email:'josharagon99@gmail.com', language:'C++', date:'03/24/2021', repo:'https://github.com/josharagon/self-care-center', status:'complete', reviewer: 'Jackson'},
    {username:'owenhallgren', summary: 'This is my first time using this language. Help me undertan OOP', email:'owenhallgren@gmail.com', language:'C#', date:'02/24/2021', repo: 'https://github.com/owenhallgren/js-fun-at-the-library', status:'', reviewer: ''},
    {username:'rdtho2525', summary: 'Pleas review my use of enumerables', email:'reggieveggie@msn.com', language:'Ruby', date:'02/01/2020', repo: 'https://github.com/JeffShepherd/Rancid-Tomatillos', status:'complete', reviewer: 'Jackson'},
    {username:'aemiers', summary: 'I am trying to set feature flags, but having issues with using the public and private modifiers. Please review how I might optimize my code.', email:'annie@gmail.com', language:'Java', date:'06/15/2021', repo: 'https://github.com/Jacksonmcguire/intention-timer', status:'', reviewer: ''},
    {username:'ConnorAndersonLarson', summary: 'I am trying to customize my WordPress website, and am new to PHP. Please review my code before I deploy it.', email:'igivehousetours@gmail.com', language:'PHP', date:'09/18/2021', repo:'https://github.com/josharagon/self-care-center', status:'', reviewer: ''},
    {username:'Shakikka', summary: 'This is my first time using Scala. How can I better optimize this machine learning application using Scala.', email:'joelToll@hotmail.com', language:'Other', date:'02/24/2021', repo: 'https://github.com/owenhallgren/js-fun-at-the-library', status:'active', reviewer: 'Jackson'},
    {username:'mattmcvey', summary: 'I am in CS101 learning C, and am very stuck. Please help me out!', email:'mcvey@hotmail.com', language:'C', date:'02/24/2021', repo: 'https://github.com/mattmcvey/flashcards-game', status:'', reviewer: ''},
    {username:'PaigeVannelli', summary: 'Trouble with gem versioning', email:'paige@hotmail.com', language:'Ruby', date:'07/24/2020', repo: 'https://github.com/PaigeVannelli/Cinematic', status:'complete', reviewer: 'Jackson'},
    {username:'monshan', summary: 'Coming from a SQL background, and this is tough! How do I go about declaring integers?', email:'monshan@hotmail.com', language:'Java', date:'09/24/2020', repo: 'https://github.com/monshan?tab=repositories', status:'active', reviewer: 'Jackson'},
    {username:'m1073496', summary: 'SQL question: how do I go about executing a cartesian join? Or should I do something different due to performance concerns?', email:'m1073496@hotmail.com', language:'Other', date:'10/24/2020', repo: 'https://github.com/m1073496/overloook', status:'', reviewer: ''},
    {username:'mattumland', summary: 'I am trying to create a celcius to fahrenheit converter. Having issues with negative numbers in my program...help please!', email:'mattumland@hotmail.com', language:'C++', date:'12/24/2020', repo: 'https://github.com/mattumland/Salon', status:'', reviewer: ''}
];

module.exports = reviewData;